SELECT COUNT(*) FROM comuni;


SELECT COUNT(*) FROM comuni WHERE id > 10000;


-- Postgres mode
DROP table IF EXISTS clienti;

CREATE TABLE clienti ( -- vecchio modo
    id SERIAL PRIMARY KEY,
    nome VARCHAR (100)
);

INSERT INTO clienti (nome) VALUES ('Luigi'), ('Attilio'), ('Oreste');
INSERT INTO clienti values (100, 'Ugo');
INSERT INTO clienti (nome) VALUES ('Luisa'), ('Caterina'), ('Angela'), ('Margherita');
-- INSERT INTO clienti values (10, 'Massimo');
INSERT INTO clienti (nome) VALUES ('Carlotta'), ('Antonello'), ('Sauro');
SELECT * FROM clienti;


-- ISO I mode
DROP table IF EXISTS clienti;

CREATE TABLE clienti ( -- nuovo modo ISO SQL
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR (100)
);

INSERT INTO clienti (nome) VALUES ('Luigi'), ('Attilio'), ('Oreste');
INSERT INTO clienti values (100, 'Ugo');
INSERT INTO clienti (nome) VALUES ('Luisa'), ('Caterina'), ('Angela'), ('Margherita');
--INSERT INTO clienti values (10, 'Massimo');
INSERT INTO clienti (nome) VALUES ('Carlotta'), ('Antonello'), ('Sauro');

SELECT * FROM clienti;

-- ISO II mode
DROP table IF EXISTS clienti;

CREATE TABLE clienti ( -- nuovo modo ISO SQL
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR (100)
);

INSERT INTO clienti (nome) VALUES ('Luigi'), ('Attilio'), ('Oreste');
-- INSERT INTO clienti values (100, 'Ugo');
INSERT INTO clienti (nome) VALUES ('Luisa'), ('Caterina'), ('Angela'), ('Margherita');
-- INSERT INTO clienti values (10, 'Massimo');
INSERT INTO clienti (nome) VALUES ('Carlotta'), ('Antonello'), ('Sauro');

SELECT * FROM clienti;





